spring:
  application:
    name: ServiceOne
  #freemarker配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates
#druid数据源相关配置配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=UTF-8&amp;tinyInt1isBit=false
    username: liuzhiqiang
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource

    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis配置数据
  redis:
    hostName: 192.168.5.250
    port: 6379
    database: 2
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 5000
#mybatis 配置信息
mybatis:
  type-aliases-package: com.liuzhiqiang.model
  mapperLocations: classpath:/mappers/**/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8081
