spring:
  application:
    name: service-one
  #freemarker配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/templates
#druid数据源相关配置配置
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&amp;characterEncoding=UTF-8&amp;tinyInt1isBit=false
    username: root
    password: lzq199528
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  #redis配置数据
  redis:
    hostName: localhost
    port: 6379
    database: 2
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#mybatis 配置信息
mybatis:
  type-aliases-package: com.liuzhiqiang.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:/mappers/**/*.xml

# 向注册中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8081
  session:
      timeout: 36000

# 开启熔断
feign:
  hystrix:
    enabled: true


logging:
    config: classpath:log/logback.xml # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml